    {
      "action": "plan",
      "artifacts": [
        {
          "account": "training-env-examples",
          "artifact": {
            "artifactAccount": "training-env-examples",
            "id": "b3a9db15-5a7b-49a3-a54c-8a55fe8a8446",
            "reference": "https://github.com/${parameters.orgRepo}.git",
            "type": "git/repo",
            "version": "${parameters.branch}"
          }
        }
      ],
      "backendArtifact": {
        "account": "github",
        "artifact": {
          "artifactAccount": "github",
          "id": "159563b5-6739-4f73-bcf7-d04b325fb540",
          "name": "https://api.github.com/repos/${parameters.orgRepo}/contents/${parameters.subdir}/backend.tf",
          "reference": "https://api.github.com/repos/${parameters.orgRepo}/contents/${parameters.subdir}/backend.tf",
          "type": "github/file",
          "version": "${parameters.branch}"
        }
      },
      "dir": "${parameters.subdir}",
      "expectedArtifacts": [
        {
          "defaultArtifact": {
            "customKind": true,
            "id": "f018bb4d-8223-4844-a976-354be4c6f49c"
          },
          "displayName": "swift-insect-57",
          "id": "52a60a6f-9240-4dcc-ada3-322e9bc8b715",
          "matchArtifact": {
            "artifactAccount": "embedded-artifact",
            "id": "dfb77ae3-eee4-4470-bb80-a4c5dba0d057",
            "name": "planfile",
            "type": "embedded/base64"
          },
          "useDefaultArtifact": false,
          "usePriorArtifact": false
        }
      ],
      "name": "Terraform Plan",
      "overrides": {
        "region": "us-west-2",
        "s3_bucket_name": "${parameters.createBucketName}"
      },
      "refId": "1",
      "requisiteStageRefIds": [],
      "terraformVersion": "0.12.31",
      "type": "terraform",
      "workspace": "${parameters.workspace}"
    },
    {
      "failPipeline": true,
      "instructions": "Apply the Terraform Plan?",
      "judgmentInputs": [],
      "name": "Terraform Plan Manual Judgment",
      "notifications": [],
      "refId": "2",
      "requisiteStageRefIds": [
        "1"
      ],
      "type": "manualJudgment"
    },
    {
      "action": "apply",
      "artifacts": [
        {
          "account": "training-env-examples",
          "artifact": {
            "artifactAccount": "training-env-examples",
            "id": "6486827f-cb0a-4a8c-bd3d-208f972b51d2",
            "reference": "https://github.com/${parameters.orgRepo}.git",
            "type": "git/repo",
            "version": "${parameters.branch}"
          }
        },
        {
          "account": "",
          "id": "52a60a6f-9240-4dcc-ada3-322e9bc8b715"
        }
      ],
      "backendArtifact": {
        "account": "github",
        "artifact": {
          "artifactAccount": "github",
          "id": "43114979-053d-4622-bb0c-fce7f59c8e7f",
          "name": "https://api.github.com/repos/${parameters.orgRepo}/contents/${parameters.subdir}/backend.tf",
          "reference": "https://api.github.com/repos/${parameters.orgRepo}/contents/${parameters.subdir}/backend.tf",
          "type": "github/file",
          "version": "${parameters.branch}"
        }
      },
      "dir": "${parameters.subdir}",
      "expectedArtifacts": [],
      "name": "Terraform Apply",
      "overrides": {},
      "refId": "3",
      "requisiteStageRefIds": [
        "2"
      ],
      "terraformVersion": "0.12.31",
      "type": "terraform",
      "workspace": "${parameters.workspace}"
    },
    {
      "action": "output",
      "artifacts": [
        {
          "account": "training-env-examples",
          "artifact": {
            "artifactAccount": "training-env-examples",
            "id": "92d290b5-b6cc-4808-b122-efe99a11b9de",
            "reference": "https://github.com/${parameters.orgRepo}.git",
            "type": "git/repo",
            "version": "${parameters.branch}"
          }
        },
        {
          "account": "",
          "id": "52a60a6f-9240-4dcc-ada3-322e9bc8b715"
        }
      ],
      "backendArtifact": {
        "account": "github",
        "artifact": {
          "artifactAccount": "github",
          "id": "f8424082-b440-42e6-a40c-32ccc9f09411",
          "name": "https://api.github.com/repos/${parameters.orgRepo}/contents/${parameters.subdir}/backend.tf",
          "reference": "https://api.github.com/repos/${parameters.orgRepo}/contents/${parameters.subdir}/backend.tf",
          "type": "github/file",
          "version": "${parameters.branch}"
        }
      },
      "dir": "${parameters.subdir}",
      "name": "Terraform Output",
      "overrides": {},
      "refId": "4",
      "requisiteStageRefIds": [
        "3"
      ],
      "terraformVersion": "0.12.31",
      "type": "terraform"
    },
    {
      "account": "jmoon-kubernetes",
      "alias": "runJob",
      "application": "terraformer",
      "cloudProvider": "kubernetes",
      "consumeArtifactSource": "propertyFile",
      "credentials": "jmoon-kubernetes",
      "expectedArtifacts": [],
      "manifest": {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
          "generateName": "welcome-"
        },
        "spec": {
          "backoffLimit": 0,
          "template": {
            "metadata": {
              "name": "welcome"
            },
            "spec": {
              "containers": [
                {
                  "command": [
                    "/bin/sh",
                    "-c",
                    "wget https://gist.githubusercontent.com/alchen99/d222f873b9e4b05339e0dedbf57a5a5e/raw/ad6c103d553c262af11af7b283eb6f0c4d2aaed5/nginx.stub;  sed -e 's/CHANGEME/${parameters.welcome}/g' nginx.stub > index.nginx-debian.html;   aws s3 cp index.nginx-debian.html s3://${parameters.createBucketName}/index.nginx-debian.html;   echo '#!/bin/bash' > userdata.txt;  echo 'sudo aws s3 cp s3://${parameters.createBucketName}/index.nginx-debian.html /var/www/html/index.nginx-debian.html' >> userdata.txt;  echo 'sudo service nginx start' >> userdata.txt; ls -l;  echo SPINNAKER_PROPERTY_B64USERDATA=\"`cat userdata.txt | base64 -w 0`\""
                  ],
                  "image": "alchen99/k8s-debug:latest",
                  "name": "welcome"
                }
              ],
              "restartPolicy": "Never"
            }
          },
          "ttlSecondsAfterFinished": 600
        }
      },
      "name": "Run Job Create File and Copy to S3",
      "propertyFile": "welcome ",
      "refId": "5",
      "requisiteStageRefIds": [
        "4"
      ],
      "source": "text",
      "type": "runJobManifest"
    },
    {
      "amiName": "nginx-test",
      "baseLabel": "release",
      "baseOs": "focal",
      "cloudProviderType": "aws",
      "extendedAttributes": {
        "aws_associate_public_ip_address": "false",
        "aws_ena_support": "true"
      },
      "name": "Bake",
      "package": "awscli nginx",
      "refId": "6",
      "region": "us-west-2",
      "regions": [
        "us-west-2"
      ],
      "requisiteStageRefIds": [],
      "storeType": "ebs",
      "type": "bake",
      "user": "admin@alcspintest.com",
      "vmType": "hvm"
    },
    {
      "clusters": [
        {
          "account": "jmoon-aws",
          "application": "jmoon",
          "associatePublicIpAddress": true,
          "availabilityZones": {
            "us-west-2": [
              "us-west-2a",
              "us-west-2b",
              "us-west-2c",
              "us-west-2d"
            ]
          },
          "base64UserData": "${vmuserdata}",
          "capacity": {
            "desired": 1,
            "max": 1,
            "min": 1
          },
          "cloudProvider": "aws",
          "cooldown": 10,
          "copySourceCustomBlockDeviceMappings": false,
          "delayBeforeDisableSec": 0,
          "delayBeforeScaleDownSec": 0,
          "ebsOptimized": false,
          "enabledMetrics": [],
          "freeFormDetails": "testing",
          "healthCheckGracePeriod": 600,
          "healthCheckType": "EC2",
          "iamRole": "BaseIAMRole",
          "instanceMonitoring": false,
          "instanceType": "t2.nano",
          "interestingHealthProviderNames": [
            "Amazon"
          ],
          "keyPair": "jmoon-key",
          "loadBalancers": [],
          "maxRemainingAsgs": 2,
          "moniker": {
            "app": "jmoon",
            "detail": "testing",
            "stack": "stack"
          },
          "provider": "aws",
          "rollback": {
            "onFailure": false
          },
          "scaleDown": false,
          "securityGroups": [
            "sg-06e4ff5a3ecae5df4"
          ],
          "spotPrice": "",
          "stack": "stack",
          "strategy": "redblack",
          "subnetType": "test-training-b",
          "suspendedProcesses": [],
          "tags": {
            "owner": "justin.moon@armory.io"
          },
          "targetGroups": [],
          "targetHealthyDeployPercentage": 100,
          "terminationPolicies": [
            "Default"
          ],
          "useAmiBlockDeviceMappings": false
        }
      ],
      "name": "Deploy",
      "refId": "7",
      "requisiteStageRefIds": [
        "6",
        "8"
      ],
      "type": "deploy"
    },
    {
      "failOnFailedExpressions": true,
      "name": "Evaluate Variables",
      "refId": "8",
      "requisiteStageRefIds": [
        "5"
      ],
      "type": "evaluateVariables",
      "variables": [
        {
          "key": "vmuserdata",
          "value": "${#stage('Run Job Create File and Copy to S3').outputs.b64userdata}"
        }
      ]
    }
